"""initial schema

Revision ID: 475044acf976
Revises: 
Create Date: 2026-09-14 10:04:51.701819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '475044acf976'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_types',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('knowledge_base_items',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=64)), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_knowledge_base_items_category'), 'knowledge_base_items', ['category'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('farms',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location_name', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('area_hectares', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farms_owner_id'), 'farms', ['owner_id'], unique=False)
    op.create_table('ai_conversations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_conversations_farm_id'), 'ai_conversations', ['farm_id'], unique=False)
    op.create_index(op.f('ix_ai_conversations_user_id'), 'ai_conversations', ['user_id'], unique=False)
    op.create_table('documents',
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Enum('farm', 'parcel', 'row', 'tree', 'activity', 'cost', 'disease_case', 'knowledge_base_item', name='attachment_entity_type'), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_entity_id'), 'documents', ['entity_id'], unique=False)
    op.create_index(op.f('ix_documents_entity_type'), 'documents', ['entity_type'], unique=False)
    op.create_index(op.f('ix_documents_farm_id'), 'documents', ['farm_id'], unique=False)
    op.create_table('parcels',
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('area_hectares', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'code', name='uq_parcels_farm_code')
    )
    op.create_index(op.f('ix_parcels_farm_id'), 'parcels', ['farm_id'], unique=False)
    op.create_table('photos',
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', postgresql.ENUM('farm', 'parcel', 'row', 'tree', 'activity', 'cost', 'disease_case', 'knowledge_base_item', name='attachment_entity_type', create_type=False), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photos_entity_id'), 'photos', ['entity_id'], unique=False)
    op.create_index(op.f('ix_photos_entity_type'), 'photos', ['entity_type'], unique=False)
    op.create_index(op.f('ix_photos_farm_id'), 'photos', ['farm_id'], unique=False)
    op.create_table('ai_messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_messages_conversation_id'), 'ai_messages', ['conversation_id'], unique=False)
    op.create_table('orchard_rows',
    sa.Column('parcel_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parcel_id', 'number', name='uq_orchard_rows_parcel_number')
    )
    op.create_index(op.f('ix_orchard_rows_parcel_id'), 'orchard_rows', ['parcel_id'], unique=False)
    op.create_table('trees',
    sa.Column('parcel_id', sa.UUID(), nullable=False),
    sa.Column('row_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('position_in_row', sa.Integer(), nullable=False),
    sa.Column('planting_year', sa.Integer(), nullable=True),
    sa.Column('variety', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('active', 'missing', 'dead', 'replaced', 'removed', name='tree_status'), nullable=False),
    sa.Column('health_status', sa.Enum('healthy', 'watch', 'diseased', 'unknown', name='health_status'), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['row_id'], ['orchard_rows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parcel_id', 'code', name='uq_trees_parcel_code'),
    sa.UniqueConstraint('row_id', 'position_in_row', name='uq_trees_row_position')
    )
    op.create_index(op.f('ix_trees_health_status'), 'trees', ['health_status'], unique=False)
    op.create_index(op.f('ix_trees_parcel_id'), 'trees', ['parcel_id'], unique=False)
    op.create_index(op.f('ix_trees_row_id'), 'trees', ['row_id'], unique=False)
    op.create_index(op.f('ix_trees_status'), 'trees', ['status'], unique=False)
    op.create_table('activities',
    sa.Column('activity_type_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('performed_on', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('planned', 'in_progress', 'completed', 'cancelled', name='activity_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('scope_type', sa.Enum('farm', 'parcel', 'row', 'tree', name='scope_type'), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('parcel_id', sa.UUID(), nullable=True),
    sa.Column('row_id', sa.UUID(), nullable=True),
    sa.Column('tree_id', sa.UUID(), nullable=True),
    sa.CheckConstraint("\n            (scope_type = 'farm' AND parcel_id IS NULL AND row_id IS NULL AND tree_id IS NULL)\n            OR (scope_type = 'parcel' AND parcel_id IS NOT NULL AND row_id IS NULL AND tree_id IS NULL)\n            OR (scope_type = 'row' AND parcel_id IS NOT NULL AND row_id IS NOT NULL AND tree_id IS NULL)\n            OR (scope_type = 'tree' AND parcel_id IS NOT NULL AND row_id IS NOT NULL AND tree_id IS NOT NULL)\n            ", name='ck_activities_scope_matches_ids'),
    sa.ForeignKeyConstraint(['activity_type_id'], ['activity_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['row_id'], ['orchard_rows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_activity_type_id'), 'activities', ['activity_type_id'], unique=False)
    op.create_index(op.f('ix_activities_farm_id'), 'activities', ['farm_id'], unique=False)
    op.create_index(op.f('ix_activities_parcel_id'), 'activities', ['parcel_id'], unique=False)
    op.create_index(op.f('ix_activities_performed_on'), 'activities', ['performed_on'], unique=False)
    op.create_index(op.f('ix_activities_row_id'), 'activities', ['row_id'], unique=False)
    op.create_index(op.f('ix_activities_scope_type'), 'activities', ['scope_type'], unique=False)
    op.create_index(op.f('ix_activities_tree_id'), 'activities', ['tree_id'], unique=False)
    op.create_table('disease_cases',
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('parcel_id', sa.UUID(), nullable=False),
    sa.Column('tree_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='disease_severity'), nullable=False),
    sa.Column('status', sa.Enum('open', 'monitoring', 'resolved', name='disease_case_status'), nullable=False),
    sa.Column('detected_on', sa.Date(), nullable=False),
    sa.Column('resolved_on', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disease_cases_farm_id'), 'disease_cases', ['farm_id'], unique=False)
    op.create_index(op.f('ix_disease_cases_parcel_id'), 'disease_cases', ['parcel_id'], unique=False)
    op.create_index(op.f('ix_disease_cases_status'), 'disease_cases', ['status'], unique=False)
    op.create_index(op.f('ix_disease_cases_tree_id'), 'disease_cases', ['tree_id'], unique=False)
    op.create_table('costs',
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('incurred_on', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('labor', 'materials', 'machinery', 'planting', 'protection', 'fertilization', 'irrigation', 'harvest', 'other', name='cost_category'), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('scope_type', postgresql.ENUM('farm', 'parcel', 'row', 'tree', name='scope_type', create_type=False), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('parcel_id', sa.UUID(), nullable=True),
    sa.Column('row_id', sa.UUID(), nullable=True),
    sa.Column('tree_id', sa.UUID(), nullable=True),
    sa.CheckConstraint("\n            (scope_type = 'farm' AND parcel_id IS NULL AND row_id IS NULL AND tree_id IS NULL)\n            OR (scope_type = 'parcel' AND parcel_id IS NOT NULL AND row_id IS NULL AND tree_id IS NULL)\n            OR (scope_type = 'row' AND parcel_id IS NOT NULL AND row_id IS NOT NULL AND tree_id IS NULL)\n            OR (scope_type = 'tree' AND parcel_id IS NOT NULL AND row_id IS NOT NULL AND tree_id IS NOT NULL)\n            ", name='ck_costs_scope_matches_ids'),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['row_id'], ['orchard_rows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_costs_activity_id'), 'costs', ['activity_id'], unique=False)
    op.create_index(op.f('ix_costs_category'), 'costs', ['category'], unique=False)
    op.create_index(op.f('ix_costs_farm_id'), 'costs', ['farm_id'], unique=False)
    op.create_index(op.f('ix_costs_incurred_on'), 'costs', ['incurred_on'], unique=False)
    op.create_index(op.f('ix_costs_parcel_id'), 'costs', ['parcel_id'], unique=False)
    op.create_index(op.f('ix_costs_row_id'), 'costs', ['row_id'], unique=False)
    op.create_index(op.f('ix_costs_scope_type'), 'costs', ['scope_type'], unique=False)
    op.create_index(op.f('ix_costs_tree_id'), 'costs', ['tree_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_costs_tree_id'), table_name='costs')
    op.drop_index(op.f('ix_costs_scope_type'), table_name='costs')
    op.drop_index(op.f('ix_costs_row_id'), table_name='costs')
    op.drop_index(op.f('ix_costs_parcel_id'), table_name='costs')
    op.drop_index(op.f('ix_costs_incurred_on'), table_name='costs')
    op.drop_index(op.f('ix_costs_farm_id'), table_name='costs')
    op.drop_index(op.f('ix_costs_category'), table_name='costs')
    op.drop_index(op.f('ix_costs_activity_id'), table_name='costs')
    op.drop_table('costs')
    op.drop_index(op.f('ix_disease_cases_tree_id'), table_name='disease_cases')
    op.drop_index(op.f('ix_disease_cases_status'), table_name='disease_cases')
    op.drop_index(op.f('ix_disease_cases_parcel_id'), table_name='disease_cases')
    op.drop_index(op.f('ix_disease_cases_farm_id'), table_name='disease_cases')
    op.drop_table('disease_cases')
    op.drop_index(op.f('ix_activities_tree_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_scope_type'), table_name='activities')
    op.drop_index(op.f('ix_activities_row_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_performed_on'), table_name='activities')
    op.drop_index(op.f('ix_activities_parcel_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_farm_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_activity_type_id'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_trees_status'), table_name='trees')
    op.drop_index(op.f('ix_trees_row_id'), table_name='trees')
    op.drop_index(op.f('ix_trees_parcel_id'), table_name='trees')
    op.drop_index(op.f('ix_trees_health_status'), table_name='trees')
    op.drop_table('trees')
    op.drop_index(op.f('ix_orchard_rows_parcel_id'), table_name='orchard_rows')
    op.drop_table('orchard_rows')
    op.drop_index(op.f('ix_ai_messages_conversation_id'), table_name='ai_messages')
    op.drop_table('ai_messages')
    op.drop_index(op.f('ix_photos_farm_id'), table_name='photos')
    op.drop_index(op.f('ix_photos_entity_type'), table_name='photos')
    op.drop_index(op.f('ix_photos_entity_id'), table_name='photos')
    op.drop_table('photos')
    op.drop_index(op.f('ix_parcels_farm_id'), table_name='parcels')
    op.drop_table('parcels')
    op.drop_index(op.f('ix_documents_farm_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_entity_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_entity_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_ai_conversations_user_id'), table_name='ai_conversations')
    op.drop_index(op.f('ix_ai_conversations_farm_id'), table_name='ai_conversations')
    op.drop_table('ai_conversations')
    op.drop_index(op.f('ix_farms_owner_id'), table_name='farms')
    op.drop_table('farms')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_knowledge_base_items_category'), table_name='knowledge_base_items')
    op.drop_table('knowledge_base_items')
    op.drop_table('activity_types')
    # ### end Alembic commands ###
